## Employee data JSON Practice

In [25]:
import json
import pandas as pd
pd.options.display.max_rows=50
pd.options.display.max_columns=10

In [2]:
with open('employees.json','r') as f:
    data = json.load(f)
data

[{'id': 1,
  'employee_id': 1,
  'first_name': 'Guendolen',
  'last_name': 'Ughelli',
  'email': 'gughelli0@alexa.com',
  'phone_number': '553-175-5693',
  'job_title': 'Office Assistant I',
  'department': 'IT',
  'hire_date': '12/26/2008',
  'salary': 87647.33,
  'manager_id': 1},
 {'id': 2,
  'employee_id': 2,
  'first_name': 'Phillida',
  'last_name': 'Pyrah',
  'email': 'ppyrah1@kickstarter.com',
  'phone_number': '555-201-4401',
  'job_title': 'Human Resources Assistant IV',
  'department': 'Finance',
  'hire_date': '4/9/2002',
  'salary': 42756.25,
  'manager_id': 2},
 {'id': 3,
  'employee_id': 3,
  'first_name': 'Imelda',
  'last_name': 'Cozens',
  'email': 'icozens2@cbsnews.com',
  'phone_number': '304-612-6065',
  'job_title': 'Research Assistant I',
  'department': 'HR',
  'hire_date': '8/16/2000',
  'salary': 122421.41,
  'manager_id': 3},
 {'id': 4,
  'employee_id': 4,
  'first_name': 'Sutton',
  'last_name': 'Rheam',
  'email': 'srheam3@hexun.com',
  'phone_number': '803-546-1238',
  'job_title': 'Community Outreach Specialist',
  'department': 'IT',
  'hire_date': '7/22/2004',
  'salary': 74683.24,
  'manager_id': 4},
 {'id': 5,
  'employee_id': 5,
  'first_name': 'Luce',
  'last_name': 'Keeley',
  'email': 'lkeeley4@devhub.com',
  'phone_number': '147-683-7968',
  'job_title': 'Business Systems Development Analyst',
  'department': 'Sales',
  'hire_date': '4/23/2005',
  'salary': 114300.9,
  'manager_id': 5},
 {'id': 6,
  'employee_id': 6,
  'first_name': 'Tommy',
  'last_name': 'Cortese',
  'email': 'tcortese5@google.co.uk',
  'phone_number': '807-768-7534',
  'job_title': 'GIS Technical Architect',
  'department': 'Marketing',
  'hire_date': '11/25/2003',
  'salary': 32686.77,
  'manager_id': 6},
 {'id': 7,
  'employee_id': 7,
  'first_name': 'Ophelie',
  'last_name': 'Levington',
  'email': 'olevington6@wunderground.com',
  'phone_number': '233-104-0722',
  'job_title': 'Cost Accountant',
  'department': 'IT',
  'hire_date': '3/5/2006',
  'salary': 135036.76,
  'manager_id': 7},
 {'id': 8,
  'employee_id': 8,
  'first_name': 'Lyle',
  'last_name': 'McCaughran',
  'email': 'lmccaughran7@usnews.com',
  'phone_number': '195-227-5078',
  'job_title': 'Human Resources Assistant II',
  'department': 'IT',
  'hire_date': '3/30/2018',
  'salary': 100382.85,
  'manager_id': 8},
 {'id': 9,
  'employee_id': 9,
  'first_name': 'Jandy',
  'last_name': 'Brain',
  'email': 'jbrain8@geocities.jp',
  'phone_number': '977-310-6590',
  'job_title': 'Operator',
  'department': 'IT',
  'hire_date': '12/11/2001',
  'salary': 132936.16,
  'manager_id': 9},
 {'id': 10,
  'employee_id': 10,
  'first_name': 'Sigfrid',
  'last_name': 'Cornwall',
  'email': 'scornwall9@ocn.ne.jp',
  'phone_number': '392-616-6446',
  'job_title': 'Data Coordinator',
  'department': 'IT',
  'hire_date': '5/31/2013',
  'salary': 76594.4,
  'manager_id': 10},
 {'id': 11,
  'employee_id': 11,
  'first_name': 'Yankee',
  'last_name': 'Remon',
  'email': 'yremona@163.com',
  'phone_number': '749-854-8358',
  'job_title': 'Actuary',
  'department': 'Sales',
  'hire_date': '8/20/2021',
  'salary': 120388.64,
  'manager_id': 11},
 {'id': 12,
  'employee_id': 12,
  'first_name': 'Jonie',
  'last_name': 'Killen',
  'email': 'jkillenb@blogs.com',
  'phone_number': '122-193-8484',
  'job_title': 'Biostatistician I',
  'department': 'HR',
  'hire_date': '6/16/2017',
  'salary': 44987.51,
  'manager_id': 12},
 {'id': 13,
  'employee_id': 13,
  'first_name': 'Inger',
  'last_name': 'Cuesta',
  'email': 'icuestac@newsvine.com',
  'phone_number': '931-692-8712',
  'job_title': 'VP Marketing',
  'department': 'Sales',
  'hire_date': '3/14/2003',
  'salary': 105259.54,
  'manager_id': 13},
 {'id': 14,
  'employee_id': 14,
  'first_name': 'Dorice',
  'last_name': 'Crankhorn',
  'email': 'dcrankhornd@wikipedia.org',
  'phone_number': '702-620-6628',
  'job_title': 'Web Designer III',
  'department': 'Marketing',
  'hire_date': '10/17/2006',
  'salary': 48422.8,
  'manager_id': 14},
 {'id': 15,
  'employee_id': 15,
  'first_name': 'Shay',
  'last_name': 'Tommaseo',
  'email': 'stommaseoe@dell.com',
  'phone_number': '816-898-5198',
  'job_title': 'Structural Engineer',
  'department': 'IT',
  'hire_date': '9/9/2003',
  'salary': 71652.76,
  'manager_id': 15},
 {'id': 16,
  'employee_id': 16,
  'first_name': 'Ly',
  'last_name': 'Massie',
  'email': 'lmassief@csmonitor.com',
  'phone_number': '431-444-1868',
  'job_title': 'Programmer II',
  'department': 'Sales',
  'hire_date': '4/16/2014',
  'salary': 59717.74,
  'manager_id': 16},
 {'id': 17,
  'employee_id': 17,
  'first_name': 'Jennilee',
  'last_name': 'Matthewman',
  'email': 'jmatthewmang@vkontakte.ru',
  'phone_number': '819-281-4797',
  'job_title': 'Accounting Assistant I',
  'department': 'IT',
  'hire_date': '4/9/2008',
  'salary': 37385.33,
  'manager_id': 17},
 {'id': 18,
  'employee_id': 18,
  'first_name': 'Queenie',
  'last_name': 'Souter',
  'email': 'qsouterh@shareasale.com',
  'phone_number': '741-546-4813',
  'job_title': 'Administrative Officer',
  'department': 'Sales',
  'hire_date': '11/21/2018',
  'salary': 97546.45,
  'manager_id': 18},
 {'id': 19,
  'employee_id': 19,
  'first_name': 'Rudiger',
  'last_name': 'Oldrey',
  'email': 'roldreyi@hexun.com',
  'phone_number': '331-274-6590',
  'job_title': 'Web Designer III',
  'department': 'HR',
  'hire_date': '2/21/2008',
  'salary': 53578.82,
  'manager_id': 19},
 {'id': 20,
  'employee_id': 20,
  'first_name': 'Janice',
  'last_name': 'Pritty',
  'email': 'jprittyj@vkontakte.ru',
  'phone_number': '528-778-3493',
  'job_title': 'Information Systems Manager',
  'department': 'Finance',
  'hire_date': '7/30/2007',
  'salary': 45547.9,
  'manager_id': 20},
 {'id': 21,
  'employee_id': 21,
  'first_name': 'Nannette',
  'last_name': 'Meltetal',
  'email': 'nmeltetalk@goo.gl',
  'phone_number': '876-456-2771',
  'job_title': 'Social Worker',
  'department': 'Marketing',
  'hire_date': '10/15/2014',
  'salary': 84428.25,
  'manager_id': 21},
 {'id': 22,
  'employee_id': 22,
  'first_name': 'Kirsti',
  'last_name': 'Form',
  'email': 'kforml@list-manage.com',
  'phone_number': '787-291-5192',
  'job_title': 'Recruiter',
  'department': 'Finance',
  'hire_date': '7/7/2021',
  'salary': 49158.33,
  'manager_id': 22},
 {'id': 23,
  'employee_id': 23,
  'first_name': 'Vale',
  'last_name': 'Allmen',
  'email': 'vallmenm@scribd.com',
  'phone_number': '235-160-4302',
  'job_title': 'Office Assistant IV',
  'department': 'Marketing',
  'hire_date': '4/21/2013',
  'salary': 139223.25,
  'manager_id': 23},
 {'id': 24,
  'employee_id': 24,
  'first_name': 'Donetta',
  'last_name': 'Simmell',
  'email': 'dsimmelln@illinois.edu',
  'phone_number': '590-532-4177',
  'job_title': 'Associate Professor',
  'department': 'Marketing',
  'hire_date': '4/23/2009',
  'salary': 125686.49,
  'manager_id': 24},
 {'id': 25,
  'employee_id': 25,
  'first_name': 'Kenneth',
  'last_name': 'Medlen',
  'email': 'kmedleno@google.co.uk',
  'phone_number': '881-466-7433',
  'job_title': 'Recruiting Manager',
  'department': 'Finance',
  'hire_date': '11/27/2002',
  'salary': 137783.4,
  'manager_id': 25},
 {'id': 26,
  'employee_id': 26,
  'first_name': 'Corinna',
  'last_name': 'Curle',
  'email': 'ccurlep@nyu.edu',
  'phone_number': '690-524-6312',
  'job_title': 'Senior Quality Engineer',
  'department': 'Sales',
  'hire_date': '6/8/2011',
  'salary': 110526.87,
  'manager_id': 26},
 {'id': 27,
  'employee_id': 27,
  'first_name': 'Saundra',
  'last_name': 'Bradly',
  'email': 'sbradlyq@phoca.cz',
  'phone_number': '224-896-1055',
  'job_title': 'Web Developer IV',
  'department': 'Marketing',
  'hire_date': '12/12/2010',
  'salary': 37575.21,
  'manager_id': 27},
 {'id': 28,
  'employee_id': 28,
  'first_name': 'Ezri',
  'last_name': 'Fellini',
  'email': 'efellinir@chron.com',
  'phone_number': '307-912-9445',
  'job_title': 'Social Worker',
  'department': 'Finance',
  'hire_date': '1/22/2017',
  'salary': 59890.48,
  'manager_id': 28},
 {'id': 29,
  'employee_id': 29,
  'first_name': 'Gilburt',
  'last_name': 'Levy',
  'email': 'glevys@stumbleupon.com',
  'phone_number': '191-977-2804',
  'job_title': 'VP Quality Control',
  'department': 'HR',
  'hire_date': '6/29/2011',
  'salary': 43197.47,
  'manager_id': 29},
 {'id': 30,
  'employee_id': 30,
  'first_name': 'Robinetta',
  'last_name': 'Gabby',
  'email': 'rgabbyt@chron.com',
  'phone_number': '773-389-4327',
  'job_title': 'Environmental Tech',
  'department': 'IT',
  'hire_date': '4/29/2016',
  'salary': 41877.42,
  'manager_id': 30},
 {'id': 31,
  'employee_id': 31,
  'first_name': 'Allx',
  'last_name': 'Furmagier',
  'email': 'afurmagieru@netlog.com',
  'phone_number': '125-223-5321',
  'job_title': 'Health Coach III',
  'department': 'Marketing',
  'hire_date': '4/11/2014',
  'salary': 115765.76,
  'manager_id': 31},
 {'id': 32,
  'employee_id': 32,
  'first_name': 'Ardra',
  'last_name': 'Ambler',
  'email': 'aamblerv@netscape.com',
  'phone_number': '104-603-3426',
  'job_title': 'Senior Financial Analyst',
  'department': 'Finance',
  'hire_date': '12/3/2007',
  'salary': 133455.47,
  'manager_id': 32},
 {'id': 33,
  'employee_id': 33,
  'first_name': 'Mollee',
  'last_name': 'Carss',
  'email': 'mcarssw@google.de',
  'phone_number': '138-740-7534',
  'job_title': 'Paralegal',
  'department': 'IT',
  'hire_date': '12/24/2017',
  'salary': 68019.56,
  'manager_id': 33},
 {'id': 34,
  'employee_id': 34,
  'first_name': 'Johannes',
  'last_name': 'Norrey',
  'email': 'jnorreyx@cnbc.com',
  'phone_number': '751-116-3728',
  'job_title': 'Senior Editor',
  'department': 'Sales',
  'hire_date': '9/21/2004',
  'salary': 99778.27,
  'manager_id': 34},
 {'id': 35,
  'employee_id': 35,
  'first_name': 'Roxi',
  'last_name': 'Juszczak',
  'email': 'rjuszczaky@nifty.com',
  'phone_number': '620-509-3573',
  'job_title': 'Business Systems Development Analyst',
  'department': 'Finance',
  'hire_date': '6/7/2004',
  'salary': 86909.6,
  'manager_id': 35},
 {'id': 36,
  'employee_id': 36,
  'first_name': 'Enid',
  'last_name': 'Spurling',
  'email': 'espurlingz@stanford.edu',
  'phone_number': '895-481-2502',
  'job_title': 'Paralegal',
  'department': 'HR',
  'hire_date': '3/21/2000',
  'salary': 36238.56,
  'manager_id': 36},
 {'id': 37,
  'employee_id': 37,
  'first_name': 'Millicent',
  'last_name': 'Martschke',
  'email': 'mmartschke10@amazonaws.com',
  'phone_number': '661-688-3457',
  'job_title': 'Junior Executive',
  'department': 'IT',
  'hire_date': '10/20/2018',
  'salary': 40731.53,
  'manager_id': 37},
 {'id': 38,
  'employee_id': 38,
  'first_name': 'Lorette',
  'last_name': 'Ziem',
  'email': 'lziem11@angelfire.com',
  'phone_number': '552-483-1683',
  'job_title': 'Speech Pathologist',
  'department': 'HR',
  'hire_date': '9/20/2000',
  'salary': 71998.92,
  'manager_id': 38},
 {'id': 39,
  'employee_id': 39,
  'first_name': 'Ros',
  'last_name': 'Nuttall',
  'email': 'rnuttall12@exblog.jp',
  'phone_number': '730-521-2355',
  'job_title': 'Librarian',
  'department': 'Sales',
  'hire_date': '11/8/2020',
  'salary': 85019.06,
  'manager_id': 39},
 {'id': 40,
  'employee_id': 40,
  'first_name': 'Issie',
  'last_name': 'Mell',
  'email': 'imell13@friendfeed.com',
  'phone_number': '309-434-9718',
  'job_title': 'Speech Pathologist',
  'department': 'Finance',
  'hire_date': '1/2/2003',
  'salary': 145489.41,
  'manager_id': 40},
 {'id': 41,
  'employee_id': 41,
  'first_name': 'Lauri',
  'last_name': 'Currington',
  'email': 'lcurrington14@artisteer.com',
  'phone_number': '424-986-8279',
  'job_title': 'VP Sales',
  'department': 'IT',
  'hire_date': '3/17/2014',
  'salary': 96837.09,
  'manager_id': 41},
 {'id': 42,
  'employee_id': 42,
  'first_name': 'Raoul',
  'last_name': 'Bertot',
  'email': 'rbertot15@twitter.com',
  'phone_number': '479-849-5911',
  'job_title': 'Dental Hygienist',
  'department': 'Sales',
  'hire_date': '11/20/2018',
  'salary': 145257.45,
  'manager_id': 42},
 {'id': 43,
  'employee_id': 43,
  'first_name': 'Adam',
  'last_name': 'Badsworth',
  'email': 'abadsworth16@typepad.com',
  'phone_number': '211-779-4512',
  'job_title': 'Administrative Officer',
  'department': 'Marketing',
  'hire_date': '4/17/2002',
  'salary': 123077.78,
  'manager_id': 43},
 {'id': 44,
  'employee_id': 44,
  'first_name': 'Adria',
  'last_name': 'Shere',
  'email': 'ashere17@yelp.com',
  'phone_number': '713-741-3937',
  'job_title': 'Senior Developer',
  'department': 'Finance',
  'hire_date': '8/7/2019',
  'salary': 106184.06,
  'manager_id': 44},
 {'id': 45,
  'employee_id': 45,
  'first_name': 'Jeth',
  'last_name': 'Dhillon',
  'email': 'jdhillon18@answers.com',
  'phone_number': '371-455-1963',
  'job_title': 'Research Nurse',
  'department': 'Marketing',
  'hire_date': '2/1/2001',
  'salary': 69814.94,
  'manager_id': 45},
 {'id': 46,
  'employee_id': 46,
  'first_name': 'Clemmy',
  'last_name': 'Kopje',
  'email': 'ckopje19@mysql.com',
  'phone_number': '288-497-0792',
  'job_title': 'Associate Professor',
  'department': 'Marketing',
  'hire_date': '2/18/2006',
  'salary': 142608.62,
  'manager_id': 46},
 {'id': 47,
  'employee_id': 47,
  'first_name': 'Ulric',
  'last_name': 'Gregorio',
  'email': 'ugregorio1a@dailymotion.com',
  'phone_number': '213-257-0645',
  'job_title': 'Web Developer I',
  'department': 'Sales',
  'hire_date': '8/25/2006',
  'salary': 121006.48,
  'manager_id': 47},
 {'id': 48,
  'employee_id': 48,
  'first_name': 'Der',
  'last_name': 'Sivier',
  'email': 'dsivier1b@w3.org',
  'phone_number': '331-640-0105',
  'job_title': 'Environmental Specialist',
  'department': 'Marketing',
  'hire_date': '8/10/2013',
  'salary': 120118.13,
  'manager_id': 48},
 {'id': 49,
  'employee_id': 49,
  'first_name': 'Timmy',
  'last_name': 'Shepperd',
  'email': 'tshepperd1c@comsenz.com',
  'phone_number': '101-209-1107',
  'job_title': 'Executive Secretary',
  'department': 'Finance',
  'hire_date': '10/10/2003',
  'salary': 135216.48,
  'manager_id': 49},
 {'id': 50,
  'employee_id': 50,
  'first_name': 'Mill',
  'last_name': 'Partridge',
  'email': 'mpartridge1d@weather.com',
  'phone_number': '335-346-0378',
  'job_title': 'Analyst Programmer',
  'department': 'Marketing',
  'hire_date': '2/28/2015',
  'salary': 78675.43,
  'manager_id': 50}]

In [26]:
df = pd.read_json('employees.json')
df.head()

,id,employee_id,first_name,last_name,email,...,job_title,department,hire_date,salary,manager_id
0,1,1,Guendolen,Ughelli,gughelli0@alexa.com,...,Office Assistant I,IT,12/26/2008,87647.33,1
1,2,2,Phillida,Pyrah,ppyrah1@kickstarter.com,...,Human Resources Assistant IV,Finance,4/9/2002,42756.25,2
2,3,3,Imelda,Cozens,icozens2@cbsnews.com,...,Research Assistant I,HR,8/16/2000,122421.41,3
3,4,4,Sutton,Rheam,srheam3@hexun.com,...,Community Outreach Specialist,IT,7/22/2004,74683.24,4
4,5,5,Luce,Keeley,lkeeley4@devhub.com,...,Business Systems Development Analyst,Sales,4/23/2005,114300.90,5

In [4]:
# sort the employees by salary descending
df.sort_values(by='salary',ascending=False).head()

,id,employee_id,first_name,last_name,email,phone_number,job_title,department,hire_date,salary,manager_id
39,40,40,Issie,Mell,imell13@friendfeed.com,309-434-9718,Speech Pathologist,Finance,1/2/2003,145489.41,40
41,42,42,Raoul,Bertot,rbertot15@twitter.com,479-849-5911,Dental Hygienist,Sales,11/20/2018,145257.45,42
45,46,46,Clemmy,Kopje,ckopje19@mysql.com,288-497-0792,Associate Professor,Marketing,2/18/2006,142608.62,46
22,23,23,Vale,Allmen,vallmenm@scribd.com,235-160-4302,Office Assistant IV,Marketing,4/21/2013,139223.25,23
24,25,25,Kenneth,Medlen,kmedleno@google.co.uk,881-466-7433,Recruiting Manager,Finance,11/27/2002,137783.40,25

In [5]:
# fetch the employee name , employee_id , hire_date , salary whose salary is greater than 80000
val = []
for e in data:
    if e['salary']>80000:
        val.append((e['employee_id'],e['first_name'],e['last_name'],e['salary'],e['hire_date']))
print(val)

[(1, 'Guendolen', 'Ughelli', 87647.33, '12/26/2008'), (3, 'Imelda', 'Cozens', 122421.41, '8/16/2000'), (5, 'Luce', 'Keeley', 114300.9, '4/23/2005'), (7, 'Ophelie', 'Levington', 135036.76, '3/5/2006'), (8, 'Lyle', 'McCaughran', 100382.85, '3/30/2018'), (9, 'Jandy', 'Brain', 132936.16, '12/11/2001'), (11, 'Yankee', 'Remon', 120388.64, '8/20/2021'), (13, 'Inger', 'Cuesta', 105259.54, '3/14/2003'), (18, 'Queenie', 'Souter', 97546.45, '11/21/2018'), (21, 'Nannette', 'Meltetal', 84428.25, '10/15/2014'), (23, 'Vale', 'Allmen', 139223.25, '4/21/2013'), (24, 'Donetta', 'Simmell', 125686.49, '4/23/2009'), (25, 'Kenneth', 'Medlen', 137783.4, '11/27/2002'), (26, 'Corinna', 'Curle', 110526.87, '6/8/2011'), (31, 'Allx', 'Furmagier', 115765.76, '4/11/2014'), (32, 'Ardra', 'Ambler', 133455.47, '12/3/2007'), (34, 'Johannes', 'Norrey', 99778.27, '9/21/2004'), (35, 'Roxi', 'Juszczak', 86909.6, '6/7/2004'), (39, 'Ros', 'Nuttall', 85019.06, '11/8/2020'), (40, 'Issie', 'Mell', 145489.41, '1/2/2003'), (41, 'Lauri', 'Currington', 96837.09, '3/17/2014'), (42, 'Raoul', 'Bertot', 145257.45, '11/20/2018'), (43, 'Adam', 'Badsworth', 123077.78, '4/17/2002'), (44, 'Adria', 'Shere', 106184.06, '8/7/2019'), (46, 'Clemmy', 'Kopje', 142608.62, '2/18/2006'), (47, 'Ulric', 'Gregorio', 121006.48, '8/25/2006'), (48, 'Der', 'Sivier', 120118.13, '8/10/2013'), (49, 'Timmy', 'Shepperd', 135216.48, '10/10/2003')]

In [6]:
df.loc[
    df["salary"] > 80000,
    ["employee_id", "first_name", "last_name", "salary", "hire_date"]
].head()

   employee_id first_name   last_name     salary   hire_date
0            1  Guendolen     Ughelli   87647.33  12/26/2008
2            3     Imelda      Cozens  122421.41   8/16/2000
4            5       Luce      Keeley  114300.90   4/23/2005
6            7    Ophelie   Levington  135036.76    3/5/2006
7            8       Lyle  McCaughran  100382.85   3/30/2018

In [7]:
# finding the employees whose hire date was after 1st jan 2008
df.loc[
    pd.to_datetime(df["hire_date"], format="%m/%d/%Y") > pd.Timestamp("2008-01-01"),
    ["employee_id", "first_name", "last_name", "salary", "hire_date"]
].head()

    employee_id first_name   last_name     salary   hire_date
0             1  Guendolen     Ughelli   87647.33  12/26/2008
7             8       Lyle  McCaughran  100382.85   3/30/2018
9            10    Sigfrid    Cornwall   76594.40   5/31/2013
10           11     Yankee       Remon  120388.64   8/20/2021
11           12      Jonie      Killen   44987.51   6/16/2017

In [16]:
df.loc[
    df["department"] == "Finance" ,
    ["employee_id", "first_name", "last_name", "salary", "hire_date","department"]
].loc[
    df["salary"]>10000
]

    employee_id first_name last_name     salary   hire_date department
1             2   Phillida     Pyrah   42756.25    4/9/2002    Finance
19           20     Janice    Pritty   45547.90   7/30/2007    Finance
21           22     Kirsti      Form   49158.33    7/7/2021    Finance
24           25    Kenneth    Medlen  137783.40  11/27/2002    Finance
27           28       Ezri   Fellini   59890.48   1/22/2017    Finance
31           32      Ardra    Ambler  133455.47   12/3/2007    Finance
34           35       Roxi  Juszczak   86909.60    6/7/2004    Finance
39           40      Issie      Mell  145489.41    1/2/2003    Finance
43           44      Adria     Shere  106184.06    8/7/2019    Finance
48           49      Timmy  Shepperd  135216.48  10/10/2003    Finance

In [20]:
# find all the emails that contains @cbsnews.com
df.loc[df["email"].str.contains("@cbsnews.com", regex=False), ["email"]]

                  email
2  icozens2@cbsnews.com

In [22]:
finance_people = []
for d in data:
    if d['department']=='Finance' and d['salary']>10000:
        finance_people.append(d)
finance_people

[{'id': 2,
  'employee_id': 2,
  'first_name': 'Phillida',
  'last_name': 'Pyrah',
  'email': 'ppyrah1@kickstarter.com',
  'phone_number': '555-201-4401',
  'job_title': 'Human Resources Assistant IV',
  'department': 'Finance',
  'hire_date': '4/9/2002',
  'salary': 42756.25,
  'manager_id': 2},
 {'id': 20,
  'employee_id': 20,
  'first_name': 'Janice',
  'last_name': 'Pritty',
  'email': 'jprittyj@vkontakte.ru',
  'phone_number': '528-778-3493',
  'job_title': 'Information Systems Manager',
  'department': 'Finance',
  'hire_date': '7/30/2007',
  'salary': 45547.9,
  'manager_id': 20},
 {'id': 22,
  'employee_id': 22,
  'first_name': 'Kirsti',
  'last_name': 'Form',
  'email': 'kforml@list-manage.com',
  'phone_number': '787-291-5192',
  'job_title': 'Recruiter',
  'department': 'Finance',
  'hire_date': '7/7/2021',
  'salary': 49158.33,
  'manager_id': 22},
 {'id': 25,
  'employee_id': 25,
  'first_name': 'Kenneth',
  'last_name': 'Medlen',
  'email': 'kmedleno@google.co.uk',
  'phone_number': '881-466-7433',
  'job_title': 'Recruiting Manager',
  'department': 'Finance',
  'hire_date': '11/27/2002',
  'salary': 137783.4,
  'manager_id': 25},
 {'id': 28,
  'employee_id': 28,
  'first_name': 'Ezri',
  'last_name': 'Fellini',
  'email': 'efellinir@chron.com',
  'phone_number': '307-912-9445',
  'job_title': 'Social Worker',
  'department': 'Finance',
  'hire_date': '1/22/2017',
  'salary': 59890.48,
  'manager_id': 28},
 {'id': 32,
  'employee_id': 32,
  'first_name': 'Ardra',
  'last_name': 'Ambler',
  'email': 'aamblerv@netscape.com',
  'phone_number': '104-603-3426',
  'job_title': 'Senior Financial Analyst',
  'department': 'Finance',
  'hire_date': '12/3/2007',
  'salary': 133455.47,
  'manager_id': 32},
 {'id': 35,
  'employee_id': 35,
  'first_name': 'Roxi',
  'last_name': 'Juszczak',
  'email': 'rjuszczaky@nifty.com',
  'phone_number': '620-509-3573',
  'job_title': 'Business Systems Development Analyst',
  'department': 'Finance',
  'hire_date': '6/7/2004',
  'salary': 86909.6,
  'manager_id': 35},
 {'id': 40,
  'employee_id': 40,
  'first_name': 'Issie',
  'last_name': 'Mell',
  'email': 'imell13@friendfeed.com',
  'phone_number': '309-434-9718',
  'job_title': 'Speech Pathologist',
  'department': 'Finance',
  'hire_date': '1/2/2003',
  'salary': 145489.41,
  'manager_id': 40},
 {'id': 44,
  'employee_id': 44,
  'first_name': 'Adria',
  'last_name': 'Shere',
  'email': 'ashere17@yelp.com',
  'phone_number': '713-741-3937',
  'job_title': 'Senior Developer',
  'department': 'Finance',
  'hire_date': '8/7/2019',
  'salary': 106184.06,
  'manager_id': 44},
 {'id': 49,
  'employee_id': 49,
  'first_name': 'Timmy',
  'last_name': 'Shepperd',
  'email': 'tshepperd1c@comsenz.com',
  'phone_number': '101-209-1107',
  'job_title': 'Executive Secretary',
  'department': 'Finance',
  'hire_date': '10/10/2003',
  'salary': 135216.48,
  'manager_id': 49}]

In [24]:
with open('finance_json.json','w') as f:
    json.dump(finance_people,f,indent=4)