## Excel Practice

In [2]:
import pandas as pd

In [4]:
df = pd.read_excel('product_catalog.xlsx')
df

       id       name    category  unitPrice
0   P1001  Product A  Category 3     115.41
1   P1002  Product B  Category 2      42.18
2   P1003  Product C  Category 1     178.91
3   P1004  Product D  Category 4     134.14
4   P1005  Product E  Category 4     194.52
5   P1006  Product F  Category 4      64.36
6   P1007  Product G  Category 5     107.90
7   P1008  Product H  Category 3      28.16
8   P1009  Product I  Category 1     130.81
9   P1010  Product J  Category 2     169.27
10  P1011  Product K  Category 4      20.00
11  P1012  Product L  Category 3      38.22
12  P1013  Product M  Category 5      63.16
13  P1014  Product N  Category 4      94.22
14  P1015  Product O  Category 3      69.47
15  P1016  Product P  Category 5     126.18
16  P1017  Product Q  Category 5      62.64
17  P1018  Product R  Category 1      50.04
18  P1019  Product S  Category 5      90.47
19  P1020  Product T  Category 3     193.27

In [11]:
# fetching the rows where product name = Product A
df.loc[
    df['name']=='Product A'
]

      id       name    category  unitPrice
0  P1001  Product A  Category 3     115.41

In [12]:
# fetch the cell value at B2
df.iloc[0, 1]

'Product A'

In [15]:
# show all the rows with category= Category A
category_3 = df.loc[
    df['category']=='Category 3'
]
category_3

       id       name    category  unitPrice
0   P1001  Product A  Category 3     115.41
7   P1008  Product H  Category 3      28.16
11  P1012  Product L  Category 3      38.22
14  P1015  Product O  Category 3      69.47
19  P1020  Product T  Category 3     193.27

In [16]:
# fetch the sum of category_3
sum(category_3['unitPrice'])

444.53000000000003

In [19]:
# get all the products for category 1 for price less than 100
df.loc[
    df['category']=='Category 1'
].loc[
    df['unitPrice']<100
]

       id       name    category  unitPrice
17  P1018  Product R  Category 1      50.04

In [22]:
# find all the products and there price where price > 100
expensive_products = df.loc[
    df['unitPrice']>100,
    ['name','unitPrice']
]
expensive_products

         name  unitPrice
0   Product A     115.41
2   Product C     178.91
3   Product D     134.14
4   Product E     194.52
6   Product G     107.90
8   Product I     130.81
9   Product J     169.27
15  Product P     126.18
19  Product T     193.27

In [21]:
# fetch the row whose product id ends with '010'  
df.loc[
    df['id'].str.endswith('010')
]

      id       name    category  unitPrice
9  P1010  Product J  Category 2     169.27

In [23]:
# export the expensive products to excel
expensive_products.to_excel('expensive_prod.xlsx',index=False)