## CSV Practice

In [2]:
import csv

In [3]:
with open('practice_data.csv','r') as f:
    reader = csv.reader(f)
    for rows in reader:
        print(rows)

['id', 'first_name', 'last_name', 'email', 'age', 'city', 'country', 'department', 'salary', 'active']
['1', 'Ava', 'Patel', 'ava.patel@example.com', '29', 'New York', 'USA', 'Engineering', '95000', 'yes']
['2', 'Liam', 'Nguyen', 'liam.nguyen@example.com', '34', 'Seattle', 'USA', 'Marketing', '78000', 'yes']
['3', 'Sofia', 'Martinez', 'sofia.martinez@example.com', '27', 'Barcelona', 'Spain', 'Sales', '68000', 'yes']
['4', 'Noah', 'Kim', 'noah.kim@example.com', '31', 'Seoul', 'South Korea', 'Finance', '82000', 'no']
['5', 'Emma', 'Johnson', 'emma.johnson@example.com', '26', 'London', 'UK', 'Support', '61000', 'yes']
['6', 'Lucas', 'Silva', 'lucas.silva@example.com', '38', 'Sao Paulo', 'Brazil', 'Operations', '74000', 'yes']
['7', 'Mila', 'Schmidt', 'mila.schmidt@example.com', '24', 'Berlin', 'Germany', 'HR', '59000', 'yes']
['8', 'James', 'Ali', 'james.ali@example.com', '41', 'Doha', 'Qatar', 'Engineering', '105000', 'yes']
['9', 'Chloe', 'Anderson', 'chloe.anderson@example.com', '30', 'Toronto', 'Canada', 'Product', '88000', 'no']
['10', 'Omar', 'Hassan', 'omar.hassan@example.com', '36', 'Cairo', 'Egypt', 'Finance', '76000', 'yes']
['11', 'Harper', 'Lee', 'harper.lee@example.com', '28', 'Melbourne', 'Australia', 'Marketing', '70000', 'yes']
['12', 'Ethan', 'Brown', 'ethan.brown@example.com', '33', 'Chicago', 'USA', 'Sales', '81000', 'yes']
['13', 'Zoe', 'Lopez', 'zoe.lopez@example.com', '29', 'Mexico City', 'Mexico', 'Support', '63000', 'no']
['14', 'Daniel', 'Chen', 'daniel.chen@example.com', '35', 'Hong Kong', 'Hong Kong', 'Engineering', '98000', 'yes']
['15', 'Aria', 'Wilson', 'aria.wilson@example.com', '27', 'Austin', 'USA', 'Product', '86000', 'yes']
['16', 'Leo', 'Petrov', 'leo.petrov@example.com', '32', 'Sofia', 'Bulgaria', 'Operations', '71000', 'no']
['17', 'Grace', 'Walker', 'grace.walker@example.com', '39', 'Manchester', 'UK', 'Finance', '92000', 'yes']
['18', 'Mason', 'Garcia', 'mason.garcia@example.com', '25', 'Madrid', 'Spain', 'Sales', '65000', 'yes']
['19', 'Nora', 'Paterson', 'nora.paterson@example.com', '31', 'Johannesburg', 'South Africa', 'HR', '67000', 'yes']
['20', 'Elijah', 'Thomas', 'elijah.thomas@example.com', '44', 'Atlanta', 'USA', 'Engineering', '110000', 'yes']
['21', 'Scarlett', 'Young', 'scarlett.young@example.com', '23', 'Oslo', 'Norway', 'Marketing', '58000', 'yes']
['22', 'Henry', 'Wright', 'henry.wright@example.com', '37', 'Paris', 'France', 'Operations', '89000', 'no']
['23', 'Lucy', 'Rossi', 'lucy.rossi@example.com', '26', 'Rome', 'Italy', 'Support', '60000', 'yes']
['24', 'Benjamin', 'King', 'benjamin.king@example.com', '42', 'Tokyo', 'Japan', 'Engineering', '101000', 'yes']
['25', 'Claire', 'Davis', 'claire.davis@example.com', '30', 'Amsterdam', 'Netherlands', 'Product', '87000', 'no']
['26', 'Alexander', 'Mora', 'alexander.mora@example.com', '34', 'Lima', 'Peru', 'Finance', '77000', 'yes']
['27', 'Penelope', 'Green', 'penelope.green@example.com', '29', 'Edinburgh', 'UK', 'Marketing', '66000', 'yes']
['28', 'Samuel', 'White', 'samuel.white@example.com', '40', 'Boston', 'USA', 'Engineering', '99000', 'yes']
['29', 'Hannah', 'Clark', 'hannah.clark@example.com', '27', 'Denver', 'USA', 'Sales', '64000', 'yes']
['30', 'Logan', 'Scott', 'logan.scott@example.com', '33', 'Dubai', 'UAE', 'Operations', '83000', 'no']
['31', 'Victoria', 'Roberts', 'victoria.roberts@example.com', '31', 'San Diego', 'USA', 'HR', '69000', 'yes']
['32', 'Jack', 'Greenwood', 'jack.greenwood@example.com', '36', 'Zurich', 'Switzerland', 'Engineering', '96000', 'yes']
['33', 'Stella', 'Evans', 'stella.evans@example.com', '24', 'Vienna', 'Austria', 'Support', '62000', 'yes']
['34', 'Julian', 'Adams', 'julian.adams@example.com', '35', 'Miami', 'USA', 'Marketing', '75000', 'no']
['35', 'Aaliyah', 'Ng', 'aaaliyah.ng@example.com', '28', 'Singapore', 'Singapore', 'Product', '90000', 'yes']
['36', 'Wyatt', 'Carter', 'wyatt.carter@example.com', '43', 'Las Vegas', 'USA', 'Finance', '108000', 'yes']
['37', 'Isabella', 'Phillips', 'isabella.phillips@example.com', '30', 'Birmingham', 'UK', 'Sales', '70000', 'yes']
['38', 'David', 'Martins', 'david.martins@example.com', '39', 'Abu Dhabi', 'UAE', 'Engineering', '102000', 'yes']
['39', 'Layla', 'Hernandez', 'layla.hernandez@example.com', '26', 'Bogota', 'Colombia', 'Support', '61000', 'no']
['40', 'Isaiah', 'Turner', 'isaiah.turner@example.com', '32', 'Stockholm', 'Sweden', 'Operations', '78000', 'yes']
['41', 'Amelia', 'Baker', 'amelia.baker@example.com', '27', 'Brussels', 'Belgium', 'Product', '85000', 'yes']
['42', 'Joseph', 'Moore', 'joseph.moore@example.com', '41', 'Montreal', 'Canada', 'Engineering', '97000', 'yes']
['43', 'Naomi', 'Thompson', 'naomi.thompson@example.com', '29', 'Dublin', 'Ireland', 'Marketing', '68000', 'no']
['44', 'Gabriel', 'Young', 'gabriel.young@example.com', '34', 'Osaka', 'Japan', 'Finance', '86000', 'yes']
['45', 'Leah', 'Hall', 'leah.hall@example.com', '31', 'Lisbon', 'Portugal', 'Sales', '72000', 'yes']
['46', 'Theodore', 'Hughes', 'theodore.hughes@example.com', '38', 'Copenhagen', 'Denmark', 'Engineering', '93000', 'yes']
['47', 'Zoey', 'Price', 'zoey.price@example.com', '25', 'Warsaw', 'Poland', 'HR', '64000', 'no']
['48', 'Christopher', 'Gomez', 'christopher.gomez@example.com', '42', 'Caracas', 'Venezuela', 'Operations', '80000', 'yes']
['49', 'Delilah', 'Cooper', 'delilah.cooper@example.com', '30', 'Nairobi', 'Kenya', 'Support', '65000', 'yes']
['50', 'Andrew', 'Brooks', 'andrew.brooks@example.com', '37', 'Reykjavik', 'Iceland', 'Product', '91000', 'yes']
['51', 'Riley', 'Foster', 'riley.foster@example.com', '33', 'Quebec City', 'Canada', 'Finance', '79000', 'no']
['52', 'Jonathan', 'Stewart', 'jonathan.stewart@example.com', '45', 'New Delhi', 'India', 'Engineering', '112000', 'yes']
['53', 'Madison', 'Collins', 'madison.collins@example.com', '28', 'Jakarta', 'Indonesia', 'Marketing', '69000', 'yes']
['54', 'Anthony', 'Rivera', 'anthony.rivera@example.com', '36', 'Lisbon', 'Portugal', 'Operations', '81000', 'yes']

In [4]:
f_read = open('practice_data.csv','r')
dicter = csv.DictReader(f_read)
print(list(dicter)[:5])

[{'id': '1', 'first_name': 'Ava', 'last_name': 'Patel', 'email': 'ava.patel@example.com', 'age': '29', 'city': 'New York', 'country': 'USA', 'department': 'Engineering', 'salary': '95000', 'active': 'yes'}, {'id': '2', 'first_name': 'Liam', 'last_name': 'Nguyen', 'email': 'liam.nguyen@example.com', 'age': '34', 'city': 'Seattle', 'country': 'USA', 'department': 'Marketing', 'salary': '78000', 'active': 'yes'}, {'id': '3', 'first_name': 'Sofia', 'last_name': 'Martinez', 'email': 'sofia.martinez@example.com', 'age': '27', 'city': 'Barcelona', 'country': 'Spain', 'department': 'Sales', 'salary': '68000', 'active': 'yes'}, {'id': '4', 'first_name': 'Noah', 'last_name': 'Kim', 'email': 'noah.kim@example.com', 'age': '31', 'city': 'Seoul', 'country': 'South Korea', 'department': 'Finance', 'salary': '82000', 'active': 'no'}, {'id': '5', 'first_name': 'Emma', 'last_name': 'Johnson', 'email': 'emma.johnson@example.com', 'age': '26', 'city': 'London', 'country': 'UK', 'department': 'Support', 'salary': '61000', 'active': 'yes'}]

In [5]:
# printing the total number of rows in csv file
count=0
with open('practice_data.csv','r') as f:
    reeder = csv.reader(f)
    # print(sum(1 for _ in reeder))
    print(len(list(reeder)))

55

In [28]:
# printing the columns 
f_opened = open('practice_data.csv','r')
red = csv.reader(f_opened)
lst = list(red)
print(lst[0])

['id', 'first_name', 'last_name', 'email', 'age', 'city', 'country', 'department', 'salary', 'active']

In [7]:
# print only 5 rows
five_rows = lst[1:6]
five_rows

[['1',
  'Ava',
  'Patel',
  'ava.patel@example.com',
  '29',
  'New York',
  'USA',
  'Engineering',
  '95000',
  'yes'],
 ['2',
  'Liam',
  'Nguyen',
  'liam.nguyen@example.com',
  '34',
  'Seattle',
  'USA',
  'Marketing',
  '78000',
  'yes'],
 ['3',
  'Sofia',
  'Martinez',
  'sofia.martinez@example.com',
  '27',
  'Barcelona',
  'Spain',
  'Sales',
  '68000',
  'yes'],
 ['4',
  'Noah',
  'Kim',
  'noah.kim@example.com',
  '31',
  'Seoul',
  'South Korea',
  'Finance',
  '82000',
  'no'],
 ['5',
  'Emma',
  'Johnson',
  'emma.johnson@example.com',
  '26',
  'London',
  'UK',
  'Support',
  '61000',
  'yes']]

In [8]:
# calculating average age
ages = list(row[4] for row in lst)[1:]
ages = sum(int(age) for age in ages)
print(ages/len(lst))

32.0

In [9]:
# counting the people by city 
cities = {}
for row in lst[1:]:
    city = row[5]
    if city in cities:
        cities[city]+=1
    else:
        cities[city]=1
print(len(cities),cities)

53 {'New York': 1, 'Seattle': 1, 'Barcelona': 1, 'Seoul': 1, 'London': 1, 'Sao Paulo': 1, 'Berlin': 1, 'Doha': 1, 'Toronto': 1, 'Cairo': 1, 'Melbourne': 1, 'Chicago': 1, 'Mexico City': 1, 'Hong Kong': 1, 'Austin': 1, 'Sofia': 1, 'Manchester': 1, 'Madrid': 1, 'Johannesburg': 1, 'Atlanta': 1, 'Oslo': 1, 'Paris': 1, 'Rome': 1, 'Tokyo': 1, 'Amsterdam': 1, 'Lima': 1, 'Edinburgh': 1, 'Boston': 1, 'Denver': 1, 'Dubai': 1, 'San Diego': 1, 'Zurich': 1, 'Vienna': 1, 'Miami': 1, 'Singapore': 1, 'Las Vegas': 1, 'Birmingham': 1, 'Abu Dhabi': 1, 'Bogota': 1, 'Stockholm': 1, 'Brussels': 1, 'Montreal': 1, 'Dublin': 1, 'Osaka': 1, 'Lisbon': 2, 'Copenhagen': 1, 'Warsaw': 1, 'Caracas': 1, 'Nairobi': 1, 'Reykjavik': 1, 'Quebec City': 1, 'New Delhi': 1, 'Jakarta': 1}

In [14]:
# finding the maximum and minimum ages
ages_lst = list(int(row[4]) for row in lst[1:])
max_age = max(ages_lst)
min_age = min(ages_lst)
print(max_age,min_age)

45 23

In [19]:
# finding names of the oldest and youngest people
for row in lst[1:]:
    if row[4]==str(max_age):
        print(f'Max age of :{row[1]}')
    if row[4]==str(min_age):
        print(f'Min age of :{row[1]}')

Min age of :Scarlett
Max age of :Jonathan

In [21]:
# calculating the average salary
avg_salary = 0
for row in lst[1:]:
    avg_salary +=int(row[8])
avg_salary/=len(lst[1:])
print(avg_salary)

80111.11111111111

In [24]:
# count of active , inactive users
active = 0
inactive = 0
for row in lst[1:]:
    if row[-1]=='yes':
        active+=1
    else:
        inactive+=1
print(active,inactive)

42 12

In [25]:
# highest and lowest paid salaries
salaries = []
for row in lst[1:]:
    salaries.append(int(row[8]))
max_salary = max(salaries)
min_salary = min(salaries)
for row in lst[1:]:
    if int(row[8])==max_salary:
        print(f'Max salary of:{row[2]}')
    if int(row[8])==min_salary:
        print(f'Min salary of:{row[2]}')

Min salary of:Young
Max salary of:Stewart

In [30]:
# filtering the rows for age > 30
age_over_30 = []
for row in lst[1:]:
    if int(row[4])>30:
        age_over_30.append(row)
print(age_over_30)

[['2', 'Liam', 'Nguyen', 'liam.nguyen@example.com', '34', 'Seattle', 'USA', 'Marketing', '78000', 'yes'], ['4', 'Noah', 'Kim', 'noah.kim@example.com', '31', 'Seoul', 'South Korea', 'Finance', '82000', 'no'], ['6', 'Lucas', 'Silva', 'lucas.silva@example.com', '38', 'Sao Paulo', 'Brazil', 'Operations', '74000', 'yes'], ['8', 'James', 'Ali', 'james.ali@example.com', '41', 'Doha', 'Qatar', 'Engineering', '105000', 'yes'], ['10', 'Omar', 'Hassan', 'omar.hassan@example.com', '36', 'Cairo', 'Egypt', 'Finance', '76000', 'yes'], ['12', 'Ethan', 'Brown', 'ethan.brown@example.com', '33', 'Chicago', 'USA', 'Sales', '81000', 'yes'], ['14', 'Daniel', 'Chen', 'daniel.chen@example.com', '35', 'Hong Kong', 'Hong Kong', 'Engineering', '98000', 'yes'], ['16', 'Leo', 'Petrov', 'leo.petrov@example.com', '32', 'Sofia', 'Bulgaria', 'Operations', '71000', 'no'], ['17', 'Grace', 'Walker', 'grace.walker@example.com', '39', 'Manchester', 'UK', 'Finance', '92000', 'yes'], ['19', 'Nora', 'Paterson', 'nora.paterson@example.com', '31', 'Johannesburg', 'South Africa', 'HR', '67000', 'yes'], ['20', 'Elijah', 'Thomas', 'elijah.thomas@example.com', '44', 'Atlanta', 'USA', 'Engineering', '110000', 'yes'], ['22', 'Henry', 'Wright', 'henry.wright@example.com', '37', 'Paris', 'France', 'Operations', '89000', 'no'], ['24', 'Benjamin', 'King', 'benjamin.king@example.com', '42', 'Tokyo', 'Japan', 'Engineering', '101000', 'yes'], ['26', 'Alexander', 'Mora', 'alexander.mora@example.com', '34', 'Lima', 'Peru', 'Finance', '77000', 'yes'], ['28', 'Samuel', 'White', 'samuel.white@example.com', '40', 'Boston', 'USA', 'Engineering', '99000', 'yes'], ['30', 'Logan', 'Scott', 'logan.scott@example.com', '33', 'Dubai', 'UAE', 'Operations', '83000', 'no'], ['31', 'Victoria', 'Roberts', 'victoria.roberts@example.com', '31', 'San Diego', 'USA', 'HR', '69000', 'yes'], ['32', 'Jack', 'Greenwood', 'jack.greenwood@example.com', '36', 'Zurich', 'Switzerland', 'Engineering', '96000', 'yes'], ['34', 'Julian', 'Adams', 'julian.adams@example.com', '35', 'Miami', 'USA', 'Marketing', '75000', 'no'], ['36', 'Wyatt', 'Carter', 'wyatt.carter@example.com', '43', 'Las Vegas', 'USA', 'Finance', '108000', 'yes'], ['38', 'David', 'Martins', 'david.martins@example.com', '39', 'Abu Dhabi', 'UAE', 'Engineering', '102000', 'yes'], ['40', 'Isaiah', 'Turner', 'isaiah.turner@example.com', '32', 'Stockholm', 'Sweden', 'Operations', '78000', 'yes'], ['42', 'Joseph', 'Moore', 'joseph.moore@example.com', '41', 'Montreal', 'Canada', 'Engineering', '97000', 'yes'], ['44', 'Gabriel', 'Young', 'gabriel.young@example.com', '34', 'Osaka', 'Japan', 'Finance', '86000', 'yes'], ['45', 'Leah', 'Hall', 'leah.hall@example.com', '31', 'Lisbon', 'Portugal', 'Sales', '72000', 'yes'], ['46', 'Theodore', 'Hughes', 'theodore.hughes@example.com', '38', 'Copenhagen', 'Denmark', 'Engineering', '93000', 'yes'], ['48', 'Christopher', 'Gomez', 'christopher.gomez@example.com', '42', 'Caracas', 'Venezuela', 'Operations', '80000', 'yes'], ['50', 'Andrew', 'Brooks', 'andrew.brooks@example.com', '37', 'Reykjavik', 'Iceland', 'Product', '91000', 'yes'], ['51', 'Riley', 'Foster', 'riley.foster@example.com', '33', 'Quebec City', 'Canada', 'Finance', '79000', 'no'], ['52', 'Jonathan', 'Stewart', 'jonathan.stewart@example.com', '45', 'New Delhi', 'India', 'Engineering', '112000', 'yes'], ['54', 'Anthony', 'Rivera', 'anthony.rivera@example.com', '36', 'Lisbon', 'Portugal', 'Operations', '81000', 'yes']]

In [31]:
# filtering the country = USA
cntry_USA = []
for row in lst[1:]:
    if row[6]=='USA':
        cntry_USA.append(row)
print(cntry_USA)

[['1', 'Ava', 'Patel', 'ava.patel@example.com', '29', 'New York', 'USA', 'Engineering', '95000', 'yes'], ['2', 'Liam', 'Nguyen', 'liam.nguyen@example.com', '34', 'Seattle', 'USA', 'Marketing', '78000', 'yes'], ['12', 'Ethan', 'Brown', 'ethan.brown@example.com', '33', 'Chicago', 'USA', 'Sales', '81000', 'yes'], ['15', 'Aria', 'Wilson', 'aria.wilson@example.com', '27', 'Austin', 'USA', 'Product', '86000', 'yes'], ['20', 'Elijah', 'Thomas', 'elijah.thomas@example.com', '44', 'Atlanta', 'USA', 'Engineering', '110000', 'yes'], ['28', 'Samuel', 'White', 'samuel.white@example.com', '40', 'Boston', 'USA', 'Engineering', '99000', 'yes'], ['29', 'Hannah', 'Clark', 'hannah.clark@example.com', '27', 'Denver', 'USA', 'Sales', '64000', 'yes'], ['31', 'Victoria', 'Roberts', 'victoria.roberts@example.com', '31', 'San Diego', 'USA', 'HR', '69000', 'yes'], ['34', 'Julian', 'Adams', 'julian.adams@example.com', '35', 'Miami', 'USA', 'Marketing', '75000', 'no'], ['36', 'Wyatt', 'Carter', 'wyatt.carter@example.com', '43', 'Las Vegas', 'USA', 'Finance', '108000', 'yes']]

In [32]:
# reading the csv file and sorting by age desc 
import pandas as pd
df = pd.read_csv('practice_data.csv')
df.head()

,id,first_name,last_name,email,age,city,country,department,salary,active
0,1,Ava,Patel,ava.patel@example.com,29,New York,USA,Engineering,95000,yes
1,2,Liam,Nguyen,liam.nguyen@example.com,34,Seattle,USA,Marketing,78000,yes
2,3,Sofia,Martinez,sofia.martinez@example.com,27,Barcelona,Spain,Sales,68000,yes
3,4,Noah,Kim,noah.kim@example.com,31,Seoul,South Korea,Finance,82000,no
4,5,Emma,Johnson,emma.johnson@example.com,26,London,UK,Support,61000,yes

In [33]:
# sort by age descending 
df.sort_values(by='age',ascending=False)

,id,first_name,last_name,email,age,city,country,department,salary,active
51,52,Jonathan,Stewart,jonathan.stewart@example.com,45,New Delhi,India,Engineering,112000,yes
19,20,Elijah,Thomas,elijah.thomas@example.com,44,Atlanta,USA,Engineering,110000,yes
35,36,Wyatt,Carter,wyatt.carter@example.com,43,Las Vegas,USA,Finance,108000,yes
47,48,Christopher,Gomez,christopher.gomez@example.com,42,Caracas,Venezuela,Operations,80000,yes
23,24,Benjamin,King,benjamin.king@example.com,42,Tokyo,Japan,Engineering,101000,yes
7,8,James,Ali,james.ali@example.com,41,Doha,Qatar,Engineering,105000,yes
41,42,Joseph,Moore,joseph.moore@example.com,41,Montreal,Canada,Engineering,97000,yes
27,28,Samuel,White,samuel.white@example.com,40,Boston,USA,Engineering,99000,yes
16,17,Grace,Walker,grace.walker@example.com,39,Manchester,UK,Finance,92000,yes
37,38,David,Martins,david.martins@example.com,39,Abu Dhabi,UAE,Engineering,102000,yes
5,6,Lucas,Silva,lucas.silva@example.com,38,Sao Paulo,Brazil,Operations,74000,yes
45,46,Theodore,Hughes,theodore.hughes@example.com,38,Copenhagen,Denmark,Engineering,93000,yes
49,50,Andrew,Brooks,andrew.brooks@example.com,37,Reykjavik,Iceland,Product,91000,yes
21,22,Henry,Wright,henry.wright@example.com,37,Paris,France,Operations,89000,no
31,32,Jack,Greenwood,jack.greenwood@example.com,36,Zurich,Switzerland,Engineering,96000,yes
53,54,Anthony,Rivera,anthony.rivera@example.com,36,Lisbon,Portugal,Operations,81000,yes
9,10,Omar,Hassan,omar.hassan@example.com,36,Cairo,Egypt,Finance,76000,yes
13,14,Daniel,Chen,daniel.chen@example.com,35,Hong Kong,Hong Kong,Engineering,98000,yes
33,34,Julian,Adams,julian.adams@example.com,35,Miami,USA,Marketing,75000,no
1,2,Liam,Nguyen,liam.nguyen@example.com,34,Seattle,USA,Marketing,78000,yes
25,26,Alexander,Mora,alexander.mora@example.com,34,Lima,Peru,Finance,77000,yes
43,44,Gabriel,Young,gabriel.young@example.com,34,Osaka,Japan,Finance,86000,yes
50,51,Riley,Foster,riley.foster@example.com,33,Quebec City,Canada,Finance,79000,no
29,30,Logan,Scott,logan.scott@example.com,33,Dubai,UAE,Operations,83000,no
11,12,Ethan,Brown,ethan.brown@example.com,33,Chicago,USA,Sales,81000,yes
39,40,Isaiah,Turner,isaiah.turner@example.com,32,Stockholm,Sweden,Operations,78000,yes
15,16,Leo,Petrov,leo.petrov@example.com,32,Sofia,Bulgaria,Operations,71000,no
44,45,Leah,Hall,leah.hall@example.com,31,Lisbon,Portugal,Sales,72000,yes
3,4,Noah,Kim,noah.kim@example.com,31,Seoul,South Korea,Finance,82000,no
30,31,Victoria,Roberts,victoria.roberts@example.com,31,San Diego,USA,HR,69000,yes
18,19,Nora,Paterson,nora.paterson@example.com,31,Johannesburg,South Africa,HR,67000,yes
48,49,Delilah,Cooper,delilah.cooper@example.com,30,Nairobi,Kenya,Support,65000,yes
24,25,Claire,Davis,claire.davis@example.com,30,Amsterdam,Netherlands,Product,87000,no
36,37,Isabella,Phillips,isabella.phillips@example.com,30,Birmingham,UK,Sales,70000,yes
8,9,Chloe,Anderson,chloe.anderson@example.com,30,Toronto,Canada,Product,88000,no
42,43,Naomi,Thompson,naomi.thompson@example.com,29,Dublin,Ireland,Marketing,68000,no
0,1,Ava,Patel,ava.patel@example.com,29,New York,USA,Engineering,95000,yes
26,27,Penelope,Green,penelope.green@example.com,29,Edinburgh,UK,Marketing,66000,yes
12,13,Zoe,Lopez,zoe.lopez@example.com,29,Mexico City,Mexico,Support,63000,no
10,11,Harper,Lee,harper.lee@example.com,28,Melbourne,Australia,Marketing,70000,yes
34,35,Aaliyah,Ng,aaaliyah.ng@example.com,28,Singapore,Singapore,Product,90000,yes
52,53,Madison,Collins,madison.collins@example.com,28,Jakarta,Indonesia,Marketing,69000,yes
14,15,Aria,Wilson,aria.wilson@example.com,27,Austin,USA,Product,86000,yes
40,41,Amelia,Baker,amelia.baker@example.com,27,Brussels,Belgium,Product,85000,yes
28,29,Hannah,Clark,hannah.clark@example.com,27,Denver,USA,Sales,64000,yes
2,3,Sofia,Martinez,sofia.martinez@example.com,27,Barcelona,Spain,Sales,68000,yes
38,39,Layla,Hernandez,layla.hernandez@example.com,26,Bogota,Colombia,Support,61000,no
4,5,Emma,Johnson,emma.johnson@example.com,26,London,UK,Support,61000,yes
22,23,Lucy,Rossi,lucy.rossi@example.com,26,Rome,Italy,Support,60000,yes
17,18,Mason,Garcia,mason.garcia@example.com,25,Madrid,Spain,Sales,65000,yes
46,47,Zoey,Price,zoey.price@example.com,25,Warsaw,Poland,HR,64000,no
32,33,Stella,Evans,stella.evans@example.com,24,Vienna,Austria,Support,62000,yes
6,7,Mila,Schmidt,mila.schmidt@example.com,24,Berlin,Germany,HR,59000,yes
20,21,Scarlett,Young,scarlett.young@example.com,23,Oslo,Norway,Marketing,58000,yes

In [35]:
# sort by salary ascending
df.sort_values(by='salary',ascending=False)

,id,first_name,last_name,email,age,city,country,department,salary,active
51,52,Jonathan,Stewart,jonathan.stewart@example.com,45,New Delhi,India,Engineering,112000,yes
19,20,Elijah,Thomas,elijah.thomas@example.com,44,Atlanta,USA,Engineering,110000,yes
35,36,Wyatt,Carter,wyatt.carter@example.com,43,Las Vegas,USA,Finance,108000,yes
7,8,James,Ali,james.ali@example.com,41,Doha,Qatar,Engineering,105000,yes
37,38,David,Martins,david.martins@example.com,39,Abu Dhabi,UAE,Engineering,102000,yes
23,24,Benjamin,King,benjamin.king@example.com,42,Tokyo,Japan,Engineering,101000,yes
27,28,Samuel,White,samuel.white@example.com,40,Boston,USA,Engineering,99000,yes
13,14,Daniel,Chen,daniel.chen@example.com,35,Hong Kong,Hong Kong,Engineering,98000,yes
41,42,Joseph,Moore,joseph.moore@example.com,41,Montreal,Canada,Engineering,97000,yes
31,32,Jack,Greenwood,jack.greenwood@example.com,36,Zurich,Switzerland,Engineering,96000,yes
0,1,Ava,Patel,ava.patel@example.com,29,New York,USA,Engineering,95000,yes
45,46,Theodore,Hughes,theodore.hughes@example.com,38,Copenhagen,Denmark,Engineering,93000,yes
16,17,Grace,Walker,grace.walker@example.com,39,Manchester,UK,Finance,92000,yes
49,50,Andrew,Brooks,andrew.brooks@example.com,37,Reykjavik,Iceland,Product,91000,yes
34,35,Aaliyah,Ng,aaaliyah.ng@example.com,28,Singapore,Singapore,Product,90000,yes
21,22,Henry,Wright,henry.wright@example.com,37,Paris,France,Operations,89000,no
8,9,Chloe,Anderson,chloe.anderson@example.com,30,Toronto,Canada,Product,88000,no
24,25,Claire,Davis,claire.davis@example.com,30,Amsterdam,Netherlands,Product,87000,no
14,15,Aria,Wilson,aria.wilson@example.com,27,Austin,USA,Product,86000,yes
43,44,Gabriel,Young,gabriel.young@example.com,34,Osaka,Japan,Finance,86000,yes
40,41,Amelia,Baker,amelia.baker@example.com,27,Brussels,Belgium,Product,85000,yes
29,30,Logan,Scott,logan.scott@example.com,33,Dubai,UAE,Operations,83000,no
3,4,Noah,Kim,noah.kim@example.com,31,Seoul,South Korea,Finance,82000,no
11,12,Ethan,Brown,ethan.brown@example.com,33,Chicago,USA,Sales,81000,yes
53,54,Anthony,Rivera,anthony.rivera@example.com,36,Lisbon,Portugal,Operations,81000,yes
47,48,Christopher,Gomez,christopher.gomez@example.com,42,Caracas,Venezuela,Operations,80000,yes
50,51,Riley,Foster,riley.foster@example.com,33,Quebec City,Canada,Finance,79000,no
39,40,Isaiah,Turner,isaiah.turner@example.com,32,Stockholm,Sweden,Operations,78000,yes
1,2,Liam,Nguyen,liam.nguyen@example.com,34,Seattle,USA,Marketing,78000,yes
25,26,Alexander,Mora,alexander.mora@example.com,34,Lima,Peru,Finance,77000,yes
9,10,Omar,Hassan,omar.hassan@example.com,36,Cairo,Egypt,Finance,76000,yes
33,34,Julian,Adams,julian.adams@example.com,35,Miami,USA,Marketing,75000,no
5,6,Lucas,Silva,lucas.silva@example.com,38,Sao Paulo,Brazil,Operations,74000,yes
44,45,Leah,Hall,leah.hall@example.com,31,Lisbon,Portugal,Sales,72000,yes
15,16,Leo,Petrov,leo.petrov@example.com,32,Sofia,Bulgaria,Operations,71000,no
36,37,Isabella,Phillips,isabella.phillips@example.com,30,Birmingham,UK,Sales,70000,yes
10,11,Harper,Lee,harper.lee@example.com,28,Melbourne,Australia,Marketing,70000,yes
30,31,Victoria,Roberts,victoria.roberts@example.com,31,San Diego,USA,HR,69000,yes
52,53,Madison,Collins,madison.collins@example.com,28,Jakarta,Indonesia,Marketing,69000,yes
2,3,Sofia,Martinez,sofia.martinez@example.com,27,Barcelona,Spain,Sales,68000,yes
42,43,Naomi,Thompson,naomi.thompson@example.com,29,Dublin,Ireland,Marketing,68000,no
18,19,Nora,Paterson,nora.paterson@example.com,31,Johannesburg,South Africa,HR,67000,yes
26,27,Penelope,Green,penelope.green@example.com,29,Edinburgh,UK,Marketing,66000,yes
17,18,Mason,Garcia,mason.garcia@example.com,25,Madrid,Spain,Sales,65000,yes
48,49,Delilah,Cooper,delilah.cooper@example.com,30,Nairobi,Kenya,Support,65000,yes
46,47,Zoey,Price,zoey.price@example.com,25,Warsaw,Poland,HR,64000,no
28,29,Hannah,Clark,hannah.clark@example.com,27,Denver,USA,Sales,64000,yes
12,13,Zoe,Lopez,zoe.lopez@example.com,29,Mexico City,Mexico,Support,63000,no
32,33,Stella,Evans,stella.evans@example.com,24,Vienna,Austria,Support,62000,yes
38,39,Layla,Hernandez,layla.hernandez@example.com,26,Bogota,Colombia,Support,61000,no
4,5,Emma,Johnson,emma.johnson@example.com,26,London,UK,Support,61000,yes
22,23,Lucy,Rossi,lucy.rossi@example.com,26,Rome,Italy,Support,60000,yes
6,7,Mila,Schmidt,mila.schmidt@example.com,24,Berlin,Germany,HR,59000,yes
20,21,Scarlett,Young,scarlett.young@example.com,23,Oslo,Norway,Marketing,58000,yes

In [37]:
# writing a new csv with id , first_name , last_name , salary using pandas
df.to_csv('practice_write_pd.csv',columns=['id','first_name','last_name','salary'],index=False)

In [29]:
# writing a new csv with id , first_name , last_name , salary
f_writer = open('practice_write_csv.csv','w')
writer = csv.writer(f_writer,delimiter=',')
writer.writerow(['id','first_name','last_name','salary'])
for row in lst[1:]:
    id = row[0]
    first_name = row[1]
    last_name = row[2]
    salary = int(row[8])
    writer.writerow([id,first_name,last_name,salary])
print('done!')

done!