# SQlite Practice

In [2]:
import sqlite3
import pandas as pd
connection  = sqlite3.connect('organisation.db')
cursor = connection.cursor()

In [5]:
# getting attendance. > 7 hours
rows = cursor.execute('select * from attendance where hours_worked>7')
for row in rows:
    print(row)

(2, 5, '2024-07-30', 'Half Day', 7.7)
(6, 37, '2024-07-29', 'Half Day', 8.0)
(9, 4, '2024-06-30', 'Half Day', 7.2)
(12, 50, '2024-06-06', 'Present', 8.3)
(15, 16, '2024-07-14', 'Present', 9.0)
(41, 18, '2024-06-08', 'Present', 8.8)

In [7]:
# find all the employees whose attendance >6
rows = cursor.execute(''' 
select e.first_name, e.last_name , e.dept_id , e.job_title , e.salary , a.hours_worked
from attendance a inner join
employees e on a.emp_id = e.emp_id
where a.hours_worked > 6
''')
for row in rows:
    print(row)

('Sara', 'Davis', 2, 'Team Lead', 78531.45, 7.7)
('Aditya', 'Miller', 4, 'HR Specialist', 111932.44, 6.3)
('Ishaan', 'Jones', 4, 'IT Administrator', 141175.54, 8.0)
('Linda', 'Johnson', 10, 'HR Specialist', 127819.75, 7.2)
('Aditya', 'Davis', 4, 'QA Engineer', 65498.05, 8.3)
('Myra', 'Nair', 8, 'Software Engineer', 144688.83, 6.6)
('Arjun', 'Miller', 8, 'Senior Engineer', 121914.95, 9.0)
('Ira', 'Kapoor', 8, 'DevOps Engineer', 130922.7, 6.5)
('Vivaan', 'Verma', 10, 'Support Agent', 92827.79, 7.0)
('Riya', 'Mehta', 6, 'Sales Executive', 114062.17, 6.9)
('Navya', 'Kapoor', 9, 'IT Administrator', 143379.55, 8.8)
('Ananya', 'Singh', 5, 'Marketing Lead', 50051.0, 6.3)
('Arjun', 'Rodriguez', 10, 'Support Agent', 62944.68, 6.1)

In [ ]:
# showing the data in dataframe format
df = pd.read_sql(sql='''
select e.first_name, e.last_name , e.dept_id , e.job_title , e.salary , a.hours_worked
from attendance a inner join
employees e on a.emp_id = e.emp_id
where a.hours_worked > 6
''' , con=connection)
df

   first_name  last_name  dept_id          job_title     salary  hours_worked
0        Sara      Davis        2          Team Lead   78531.45           7.7
1      Aditya     Miller        4      HR Specialist  111932.44           6.3
2      Ishaan      Jones        4   IT Administrator  141175.54           8.0
3       Linda    Johnson       10      HR Specialist  127819.75           7.2
4      Aditya      Davis        4        QA Engineer   65498.05           8.3
5        Myra       Nair        8  Software Engineer  144688.83           6.6
6       Arjun     Miller        8    Senior Engineer  121914.95           9.0
7         Ira     Kapoor        8    DevOps Engineer  130922.70           6.5
8      Vivaan      Verma       10      Support Agent   92827.79           7.0
9        Riya      Mehta        6    Sales Executive  114062.17           6.9
10      Navya     Kapoor        9   IT Administrator  143379.55           8.8
11     Ananya      Singh        5     Marketing Lead   50051.00           6.3
12      Arjun  Rodriguez       10      Support Agent   62944.68           6.1

In [10]:
# find the departments
dept = pd.read_sql(sql=''' 
select * from departments
''' , con=connection)
dept

   dept_id          dept_name   location      budget
0        1        Engineering  Singapore   400395.92
1        2              Sales  Singapore   695052.77
2        3          Marketing     London   451168.27
3        4    Human Resources   New York  1418059.08
4        5            Finance    Toronto   356489.90
5        6   Customer Support     Berlin   257208.82
6        7            Product   New York   593548.35
7        8              Legal    Toronto  1283633.71
8        9  IT Infrastructure    Toronto   557907.77
9       10           Research  Singapore  1462384.95

In [13]:
employees = pd.read_sql(sql=''' 
select * from employees
''' , con=connection)
employees .head()

,emp_id,first_name,last_name,email,dept_id,job_title,salary,hire_date,manager_id
0,1,Myra,Singh,myra.singh1@orgmail.com,8,Data Analyst,66991.93,2024-09-30,NaN
1,2,Aarav,Nair,aarav.nair2@orgmail.com,7,Financial Analyst,66955.20,2017-05-31,NaN
2,3,Robert,Smith,robert.smith3@orgmail.com,2,Senior Engineer,78691.64,2019-01-10,NaN
3,4,Linda,Johnson,linda.johnson4@orgmail.com,10,HR Specialist,127819.75,2023-03-08,NaN
4,5,Sara,Davis,sara.davis5@orgmail.com,2,Team Lead,78531.45,2021-03-11,NaN

In [15]:
employee_schema = pd.read_sql_query(
    "PRAGMA table_info('employees')",
    connection
)
employee_schema

   cid        name     type  notnull dflt_value  pk
0    0      emp_id  INTEGER        0       None   1
1    1  first_name     TEXT        0       None   0
2    2   last_name     TEXT        0       None   0
3    3       email     TEXT        0       None   0
4    4     dept_id  INTEGER        0       None   0
5    5   job_title     TEXT        0       None   0
6    6      salary     REAL        0       None   0
7    7   hire_date     TEXT        0       None   0
8    8  manager_id  INTEGER        0       None   0

In [4]:
# select the department where budget is > 3lac
dept_high = pd.read_sql(''' 
select * from departments where 
budget > 350000
''' , connection)
dept_high

   dept_id          dept_name   location      budget
0        1        Engineering  Singapore   400395.92
1        2              Sales  Singapore   695052.77
2        3          Marketing     London   451168.27
3        4    Human Resources   New York  1418059.08
4        5            Finance    Toronto   356489.90
5        7            Product   New York   593548.35
6        8              Legal    Toronto  1283633.71
7        9  IT Infrastructure    Toronto   557907.77
8       10           Research  Singapore  1462384.95

In [6]:
# show the projects as per department 
pd.read_sql(''' 
select 
d.dept_id as dept_id, d.dept_name as dept_name,
p.project_name as project_name 
, p.budget as project_budget , d.budget as dept_budget  
from departments d
inner join 
projects p 
on 
p.dept_id = d.dept_id
''' , connection)

,dept_id,dept_name,project_name,project_budget,dept_budget
0,9,IT Infrastructure,Website Revamp,55226.25,557907.77
1,7,Product,Mobile App Launch,11737.39,593548.35
2,3,Marketing,CRM Migration,373203.15,451168.27
3,9,IT Infrastructure,Q3 Marketing Campaign,64818.20,557907.77
4,3,Marketing,Cloud Migration,295429.69,451168.27
5,3,Marketing,Employee Portal,161046.59,451168.27
6,1,Engineering,Data Warehouse Build,336797.37,400395.92
7,6,Customer Support,Customer Feedback System,487180.14,257208.82
8,3,Marketing,API Gateway Upgrade,441893.94,451168.27
9,1,Engineering,Payroll Automation,403095.22,400395.92
10,4,Human Resources,Security Audit,197445.44,1418059.08
11,1,Engineering,AI Chatbot Rollout,107790.69,400395.92
12,8,Legal,Sales Dashboard,119232.54,1283633.71
13,4,Human Resources,Inventory System,433532.94,1418059.08
14,5,Finance,Onboarding Revamp,342963.88,356489.90
15,9,IT Infrastructure,Brand Redesign,439748.82,557907.77
16,5,Finance,Cost Optimization,28746.03,356489.90
17,10,Research,Partner Integration,223833.00,1462384.95
18,9,IT Infrastructure,Support Ticketing Tool,134814.03,557907.77
19,7,Product,R&D Prototype,188468.52,593548.35

In [8]:
# show all the projects by aggregating over dept_name and show the total costs consumed
pd.read_sql(''' 
select 
d.dept_name , sum(p.budget) as budget_consumed , d.budget as budget_provided
from departments d
inner join 
projects p
on p.dept_id = d.dept_id
group by d.dept_id
''' , connection)

           dept_name  budget_consumed  budget_provided
0        Engineering        847683.28        400395.92
1          Marketing       1271573.37        451168.27
2    Human Resources        630978.38       1418059.08
3            Finance        371709.91        356489.90
4   Customer Support        487180.14        257208.82
5            Product        200205.91        593548.35
6              Legal        119232.54       1283633.71
7  IT Infrastructure        694607.30        557907.77
8           Research        223833.00       1462384.95

In [10]:
# sort the projects by budget desc
pd.read_sql(''' 
select *
from projects
order by budget desc
''' , connection)

,project_id,project_name,dept_id,start_date,end_date,status,budget
0,8,Customer Feedback System,6,2024-03-09,2025-01-19,On Hold,487180.14
1,9,API Gateway Upgrade,3,2022-08-31,2022-12-22,In Progress,441893.94
2,16,Brand Redesign,9,2022-12-06,2023-01-19,Planned,439748.82
3,14,Inventory System,4,2023-02-13,2023-08-30,Completed,433532.94
4,10,Payroll Automation,1,2022-07-03,2023-01-19,On Hold,403095.22
5,3,CRM Migration,3,2023-10-15,2024-03-27,In Progress,373203.15
6,15,Onboarding Revamp,5,2022-12-26,2023-12-19,On Hold,342963.88
7,7,Data Warehouse Build,1,2023-01-02,2023-05-19,In Progress,336797.37
8,5,Cloud Migration,3,2023-07-13,2023-08-30,Completed,295429.69
9,18,Partner Integration,10,2023-03-21,2023-10-13,Completed,223833.00
10,11,Security Audit,4,2022-10-01,2023-01-20,Planned,197445.44
11,20,R&D Prototype,7,2022-01-02,2022-10-25,In Progress,188468.52
12,6,Employee Portal,3,2023-03-17,2023-06-20,Planned,161046.59
13,19,Support Ticketing Tool,9,2022-04-29,2022-12-12,In Progress,134814.03
14,13,Sales Dashboard,8,2022-12-25,2023-06-29,In Progress,119232.54
15,12,AI Chatbot Rollout,1,2024-05-29,2025-02-23,In Progress,107790.69
16,4,Q3 Marketing Campaign,9,2023-12-24,2024-08-28,Planned,64818.20
17,1,Website Revamp,9,2023-05-16,2023-10-21,Planned,55226.25
18,17,Cost Optimization,5,2022-07-02,2023-05-25,Completed,28746.03
19,2,Mobile App Launch,7,2024-04-29,2024-10-17,Planned,11737.39

In [5]:
# find all the high priority tasks of project with project_id=3
high_priority_tasks = pd.read_sql(''' 
select 
t.task_id , p.project_id , p.project_name , t.task_name , t.priority
from tasks t inner join projects p
on t.project_id = p.project_id
where t.priority = 'High'
''' , connection)
high_priority_tasks

    task_id  project_id           project_name              task_name priority
0         1           3          CRM Migration             Deployment     High
1         4          13        Sales Dashboard    Backend Development     High
2         8          17      Cost Optimization     Performance Tuning     High
3        15          15      Onboarding Revamp          Documentation     High
4        18          17      Cost Optimization   Frontend Development     High
5        19          10     Payroll Automation                Testing     High
6        31          13        Sales Dashboard          Client Review     High
7        37           4  Q3 Marketing Campaign  Requirement Gathering     High
8        47          12     AI Chatbot Rollout                Testing     High
9        51          13        Sales Dashboard   Frontend Development     High
10       53          15      Onboarding Revamp                Testing     High
11       55          16         Brand Redesign     Performance Tuning     High
12       56           7   Data Warehouse Build   Frontend Development     High
13       60          11         Security Audit  Requirement Gathering     High

In [6]:
# export the high priority tasks to a csv file
high_priority_tasks.to_csv('high_priority.csv',index=False)

In [14]:
# export high priority tasks to a json file
arr = high_priority_tasks.to_numpy()
arr

array([[1, 3, 'CRM Migration', 'Deployment', 'High'],
       [4, 13, 'Sales Dashboard', 'Backend Development', 'High'],
       [8, 17, 'Cost Optimization', 'Performance Tuning', 'High'],
       [15, 15, 'Onboarding Revamp', 'Documentation', 'High'],
       [18, 17, 'Cost Optimization', 'Frontend Development', 'High'],
       [19, 10, 'Payroll Automation', 'Testing', 'High'],
       [31, 13, 'Sales Dashboard', 'Client Review', 'High'],
       [37, 4, 'Q3 Marketing Campaign', 'Requirement Gathering', 'High'],
       [47, 12, 'AI Chatbot Rollout', 'Testing', 'High'],
       [51, 13, 'Sales Dashboard', 'Frontend Development', 'High'],
       [53, 15, 'Onboarding Revamp', 'Testing', 'High'],
       [55, 16, 'Brand Redesign', 'Performance Tuning', 'High'],
       [56, 7, 'Data Warehouse Build', 'Frontend Development', 'High'],
       [60, 11, 'Security Audit', 'Requirement Gathering', 'High']],
      dtype=object)

In [15]:
# preparing a proper dictionary
lst = []
for row in arr:
    value = {}
    value['task_id'] = row[0]
    value['project_id'] = row[1]
    value['project_name'] = row[2]
    value['task_name'] = row[3]
    value['priority'] = row[4]
    lst.append(value)
lst

[{'task_id': 1,
  'project_id': 3,
  'project_name': 'CRM Migration',
  'task_name': 'Deployment',
  'priority': 'High'},
 {'task_id': 4,
  'project_id': 13,
  'project_name': 'Sales Dashboard',
  'task_name': 'Backend Development',
  'priority': 'High'},
 {'task_id': 8,
  'project_id': 17,
  'project_name': 'Cost Optimization',
  'task_name': 'Performance Tuning',
  'priority': 'High'},
 {'task_id': 15,
  'project_id': 15,
  'project_name': 'Onboarding Revamp',
  'task_name': 'Documentation',
  'priority': 'High'},
 {'task_id': 18,
  'project_id': 17,
  'project_name': 'Cost Optimization',
  'task_name': 'Frontend Development',
  'priority': 'High'},
 {'task_id': 19,
  'project_id': 10,
  'project_name': 'Payroll Automation',
  'task_name': 'Testing',
  'priority': 'High'},
 {'task_id': 31,
  'project_id': 13,
  'project_name': 'Sales Dashboard',
  'task_name': 'Client Review',
  'priority': 'High'},
 {'task_id': 37,
  'project_id': 4,
  'project_name': 'Q3 Marketing Campaign',
  'task_name': 'Requirement Gathering',
  'priority': 'High'},
 {'task_id': 47,
  'project_id': 12,
  'project_name': 'AI Chatbot Rollout',
  'task_name': 'Testing',
  'priority': 'High'},
 {'task_id': 51,
  'project_id': 13,
  'project_name': 'Sales Dashboard',
  'task_name': 'Frontend Development',
  'priority': 'High'},
 {'task_id': 53,
  'project_id': 15,
  'project_name': 'Onboarding Revamp',
  'task_name': 'Testing',
  'priority': 'High'},
 {'task_id': 55,
  'project_id': 16,
  'project_name': 'Brand Redesign',
  'task_name': 'Performance Tuning',
  'priority': 'High'},
 {'task_id': 56,
  'project_id': 7,
  'project_name': 'Data Warehouse Build',
  'task_name': 'Frontend Development',
  'priority': 'High'},
 {'task_id': 60,
  'project_id': 11,
  'project_name': 'Security Audit',
  'task_name': 'Requirement Gathering',
  'priority': 'High'}]

In [17]:
import json
with open('high_priority.json','w') as f:
    json.dump(lst,f,indent=True)